services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV
  
  mondodb:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ahmadsamehh
      - MONGO_INITDB_ROOT_PASSWORD=66788