services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ahmadsamehh
      - MONGO_INITDB_ROOT_PASSWORD=66788
    volumes:
      - mongodb-volume:/data/db

volumes:
  mongodb-volume:
