services:
  node-app:
    container_name: node-docker-production-container
    image: node-docker-production-image
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
    command: npm start