services:
  node-app:
    container_name: node-docker-development-container
    image: node-docker-development-image
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_IP=${MONGO_IP}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

 